"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),vm=require("node:vm"),fs=require("node:fs"),path=require("node:path");
const gate=require("../src/config/financialOperations");
async function disabled(fn){const previous=process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED;delete process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED;try{await fn();}finally{if(previous===undefined)delete process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED;else process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED=previous;}}
function load(file,dependencies){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../",file),"utf8"),{module,exports:module.exports,process:{env:{STRIPE_SECRET_KEY:"sk_test_synthetic"}},require(name){if(Object.hasOwn(dependencies,name))return dependencies[name];throw Error("Unexpected import: "+name);},console,Buffer},{filename:file});return module.exports;}
test("reservation disabled before validation, reads or stock writes",()=>disabled(async()=>{let effects=0;const product=new Proxy({}, {get(){effects++;throw Error("unexpected database access");}});const reserve=require("../src/services/inventoryReservation").reserveProductStock;await assert.rejects(reserve(product,"synthetic",1,{}),{code:"FINANCIAL_OPERATIONS_DISABLED"});await assert.rejects(reserve(product,null,0,null),{code:"FINANCIAL_OPERATIONS_DISABLED"});assert.equal(effects,0);}));
test("exported Stripe facade blocks every mutation, retains reads and hides internals",()=>disabled(async()=>{let mutations=0,reads=0;const namespaces=["accounts","accountLinks","customers","ephemeralKeys","paymentIntents","refunds","transfers","webhooks"];
const sdk={checkout:{sessions:{}}};for(const name of namespaces)sdk[name]={};for(const resource of [...namespaces.map(n=>sdk[n]),sdk.checkout.sessions])for(const method of ["create","cancel","expire","retrieve","constructEvent"])resource[method]=function(){assert.ok(this===resource);if(method==="retrieve"||method==="constructEvent"){reads++;return "read";}mutations++;return "mutation";};
const exported=load("src/payments/stripeService.js",{"stripe":function(){return sdk;},"../config/returnUrls":{validateReturnUrl:v=>v},"../config/financialOperations":gate}).stripe;
for(const resource of [...namespaces.map(n=>exported[n]),exported.checkout.sessions])for(const method of Object.keys(resource)){if(method==="retrieve"||method==="constructEvent")assert.equal(resource[method](),"read");else assert.throws(()=>resource[method](),{code:"FINANCIAL_OPERATIONS_DISABLED"});}
assert.equal(mutations,0);assert.ok(reads>0);assert.equal(exported.rawRequest,undefined);assert.equal(exported._requestSender,undefined);process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED="true";assert.equal(exported.transfers.create(),"mutation");assert.equal(mutations,1);delete process.env.ALAIA_FINANCIAL_OPERATIONS_ENABLED;
}));
test("real financial routers reject before simulated auth, ledger, database and Stripe",()=>disabled(async()=>{
const express=require("express"),http=require("node:http");let effects=0;const effect=(q,r,n)=>{effects++;if(n)n();else r.json({ok:true});};const handlers=new Proxy({}, {get(){return (q,r)=>{effects++;r.json({ok:true});};}});
const deps={express,crypto:require("node:crypto"),mongoose:{},"express-validator":require("express-validator"),"../models/Orden":{},"../models/Producto":{},"../middleware/auth":{proteger:effect,soloAdmin:effect},"../middleware/firebaseAuth":{verificarFirebase:effect},"../services/checkoutLifecycle":{prepareCheckout:effect,getLifecycle:effect},"../dto/publicOrder":{toPublicOrder:effect},"../services/checkoutPricing":{calculateCheckoutPricing:effect,normalizeCheckoutItems:effect},"../payments/stripeWebhookController":handlers,"../controllers/ordenController":handlers,"../payments/stripeService":handlers,"../payments/stripeController":handlers,"../controllers/adminPayoutController":handlers,"../controllers/adminOrdenController":handlers,"../controllers/ordenTimelineController":handlers,"../controllers/ordenRealtimeController":handlers,"../controllers/vendedorController":handlers};
const app=express();app.use(gate.financialWriteGuard);for(const [prefix,file]of [["/api/stripe","stripeRoutes"],["/api/payments","paymentsRoutes"],["/api/admin/payouts","adminPayoutRoutes"],["/api/ordenes","ordenRoutes"],["/api/ordenes/admin","adminOrdenRoutes"],["/api/vendedor","vendedorRoutes"]])app.use(prefix,load("src/routes/"+file+".js",deps));app.get("/healthz",(q,r)=>r.sendStatus(200));app.get("/readyz",(q,r)=>r.sendStatus(503));
const server=http.createServer(app);try{await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve);});const request=(method,url)=>new Promise((resolve,reject)=>{const req=http.request({host:"127.0.0.1",port:server.address().port,path:url,method},res=>{let body="";res.on("data",c=>body+=c);res.on("end",()=>resolve({status:res.statusCode,body}));});req.on("error",reject);req.end();});
for(const url of ["/api/ordenes/crear","/api/vendedor/me/stripe/onboarding","/api/vendedor/me/stripe/sync","/api/stripe/checkout","/api/stripe/payment-sheet","/api/stripe/web/checkout-intent/cancel","/api/stripe/checkout-intent/cancel","/api/stripe/webhook","/api/payments/stripe/checkout","/api/payments/stripe/checkout-carrito","/api/payments/stripe/checkout-orden","/api/admin/payouts/0123456789abcdef01234567/retry"]){const result=await request("POST",url);assert.equal(result.status,503);assert.equal(JSON.parse(result.body).code,"FINANCIAL_OPERATIONS_DISABLED");}for(const url of ["/api/ordenes/admin/0123456789abcdef01234567/estado","/api/ordenes/admin/0123456789abcdef01234567/pago","/api/ordenes/admin/0123456789abcdef01234567/fulfillment"]){assert.equal((await request("PUT",url)).status,503);}assert.equal(effects,0);assert.equal((await request("GET","/healthz")).status,200);assert.equal((await request("GET","/readyz")).status,503);assert.equal((await request("GET","/api/payments/estado")).status,200);assert.ok(effects>0);
}finally{await new Promise(resolve=>server.close(resolve));}}));
